# Numpy, libreria para ciencia de datos

In [1]:
import numpy as np 
#pip install numpy

In [2]:
def creaArray(fila,columna):
  array = np.random.random((fila,columna))
  return array

In [3]:
array_1d=np.array([1,4,3])
print(array_1d)


[1 4 3]


In [4]:
array_1d

array([1, 4, 3])

In [5]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [6]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [7]:
print(array_3d)

[[[1.6 4.5 2. ]
  [1.  5.8 9. ]]

 [[7.  5.  9.3]
  [8.  1.4 3. ]]

 [[3.  5.  3. ]
  [7.  2.  9. ]]]


# Creando Arrays

In [10]:
#De ceros con 3 filas y 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
print(np.zeros((4,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#De unos con 2 dimensiones 4 filas 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [13]:
#Intervalo y saltos
np.arange(12,31,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [14]:
#Intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [15]:
#Valor dado
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [18]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.82469762, 0.31992777, 0.15185693, 0.79176233],
       [0.39952823, 0.31338382, 0.09178858, 0.56704907],
       [0.18703595, 0.39341763, 0.5089014 , 0.32791518],
       [0.32142953, 0.09954538, 0.88141911, 0.96265615]])

In [21]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Grabar y cargar

In [22]:
#Grabar
#np.save('mi_array',np.random.random((3,3)))
np.save('mi_array_3d',array_3d)

In [23]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [24]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [25]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
print(array_2d)

[[1. 4. 2.]
 [5. 2. 3.]]


# Tipos de datos

In [26]:
#Enteros
np.int64

numpy.int64

In [27]:
#Decimal, numero doble precision o de punto flotante
np.float64

numpy.float64

In [37]:
#Complejos
np.complex128

numpy.complex128

In [30]:
#Boolean
np.bool_

numpy.bool

In [38]:
#Objetos
np.object_

numpy.object_

In [40]:
#Cadenas
np.bytes_

numpy.bytes_

In [42]:
np.str_

numpy.str_

# Propiedades y caracteristicas

In [43]:
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [44]:
#Dimension o forma
array_3d.shape

(3, 2, 3)

In [45]:
#Longitud
len(array_3d)

3

In [46]:
#Numero de dimensiones
array_3d.ndim

3

In [47]:
#Tamaño o numero de elementos
array_3d.size

18

In [48]:
#Tipos de datos
array_3d.dtype

dtype('float64')

In [49]:
array_3d.dtype.name

'float64'

In [50]:
#Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

# Ayuda

In [51]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> import numpy as np
>>> x = np.arange(4).reshape((2, 2))
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int64')   # may vary (OS, bitness)
>>> isinstance(x.dtype, np.dtype)
True


# Operadores Aritmeticos

In [52]:
#Arrays de ejemplos
array1=np.random.random((4,4))
array1

array([[0.19450603, 0.16241982, 0.48592612, 0.72233632],
       [0.40394053, 0.64487742, 0.77242924, 0.23505739],
       [0.62586753, 0.54270714, 0.08846162, 0.64608525],
       [0.38565532, 0.87357231, 0.5600041 , 0.7135091 ]])

In [53]:
array2=np.random.random((4,4))
array2

array([[0.84940491, 0.11202782, 0.62300524, 0.23396045],
       [0.01332861, 0.82326831, 0.99396794, 0.78958293],
       [0.70265808, 0.04450586, 0.90760406, 0.24555561],
       [0.93844585, 0.1386971 , 0.70168452, 0.63690189]])

In [54]:
#Suma
array3=array1+array2
array3

array([[1.04391094, 0.27444764, 1.10893136, 0.95629677],
       [0.41726914, 1.46814573, 1.76639717, 1.02464032],
       [1.32852561, 0.587213  , 0.99606568, 0.89164086],
       [1.32410117, 1.01226941, 1.26168862, 1.350411  ]])

In [55]:
#Otra opcion de suma
array3=np.add(array1,array2)
array3

array([[1.04391094, 0.27444764, 1.10893136, 0.95629677],
       [0.41726914, 1.46814573, 1.76639717, 1.02464032],
       [1.32852561, 0.587213  , 0.99606568, 0.89164086],
       [1.32410117, 1.01226941, 1.26168862, 1.350411  ]])

In [56]:
#Resta
array3=array1-array2
array3

array([[-0.65489888,  0.05039201, -0.13707912,  0.48837586],
       [ 0.39061192, -0.17839089, -0.2215387 , -0.55452553],
       [-0.07679055,  0.49820128, -0.81914245,  0.40052963],
       [-0.55279053,  0.73487521, -0.14168043,  0.07660721]])

In [57]:
#Multiplica
array3=np.multiply(array1,array2)
array3

array([[0.16521438, 0.01819554, 0.30273452, 0.16899813],
       [0.00538396, 0.53090714, 0.76776989, 0.18559731],
       [0.43977088, 0.02415365, 0.08028812, 0.15864986],
       [0.36191663, 0.12116194, 0.39294621, 0.4544353 ]])

In [58]:
#Divide
array3=array1/array2
array3

array([[ 0.22899094,  1.4498169 ,  0.77997116,  3.08742912],
       [30.30628081,  0.78331379,  0.77711685,  0.29769817],
       [ 0.8907142 , 12.19405949,  0.09746719,  2.63111576],
       [ 0.41095106,  6.29841811,  0.79808529,  1.12028102]])

In [59]:
array3=np.divide(array1,array2)
array3

array([[ 0.22899094,  1.4498169 ,  0.77997116,  3.08742912],
       [30.30628081,  0.78331379,  0.77711685,  0.29769817],
       [ 0.8907142 , 12.19405949,  0.09746719,  2.63111576],
       [ 0.41095106,  6.29841811,  0.79808529,  1.12028102]])

In [60]:
np.exp(array1)

array([[1.21471081, 1.176354  , 1.62567989, 2.05923863],
       [1.49771488, 1.90575341, 2.16501921, 1.26498137],
       [1.86986742, 1.72065863, 1.09249232, 1.90805662],
       [1.4705777 , 2.39545289, 1.75067968, 2.04114128]])

In [61]:
np.sin(array1)

array([[0.1932819 , 0.16170665, 0.46702748, 0.66113933],
       [0.39304478, 0.60110048, 0.69787716, 0.2328988 ],
       [0.58580059, 0.51645604, 0.08834629, 0.60206531],
       [0.3761664 , 0.76662758, 0.53118967, 0.65449092]])

In [62]:
np.cos(array2)

array([[0.66043011, 0.99373144, 0.81212863, 0.97275587],
       [0.99991118, 0.67982796, 0.54536825, 0.70414152],
       [0.76312711, 0.99900978, 0.61563559, 0.97000241],
       [0.59104238, 0.99039697, 0.7637559 , 0.80394208]])

In [63]:
np.log(array2)

array([[-0.16321928, -2.18900806, -0.47320034, -1.45260318],
       [-4.31784259, -0.19447312, -0.00605033, -0.23625041],
       [-0.35288488, -3.11213435, -0.09694705, -1.40423182],
       [-0.06353012, -1.97546288, -0.35427137, -0.45113965]])

In [64]:
#Producto de matrices
array1.dot(array2)

array([[1.18669265, 0.27731769, 1.23049911, 0.7531299 ],
       [1.11504667, 0.64313913, 1.7586406 , 0.94307315],
       [1.20732278, 0.61045537, 1.46298839, 1.00815571],
       [1.40230209, 0.88627363, 2.11748844, 1.37193333]])

# Comparacion

== != < > <= >= and or

In [65]:
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [66]:
array1<0.5

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [ True, False, False, False]])

In [67]:
array1

array([[0.19450603, 0.16241982, 0.48592612, 0.72233632],
       [0.40394053, 0.64487742, 0.77242924, 0.23505739],
       [0.62586753, 0.54270714, 0.08846162, 0.64608525],
       [0.38565532, 0.87357231, 0.5600041 , 0.7135091 ]])

In [68]:
array3<=0.4

array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [69]:
array3

array([[ 0.22899094,  1.4498169 ,  0.77997116,  3.08742912],
       [30.30628081,  0.78331379,  0.77711685,  0.29769817],
       [ 0.8907142 , 12.19405949,  0.09746719,  2.63111576],
       [ 0.41095106,  6.29841811,  0.79808529,  1.12028102]])

# Estadisticos basicos y otras funciones

In [70]:
array1=creaArray(5,5)
array1

array([[0.96720219, 0.3039706 , 0.62661212, 0.63939482, 0.44461414],
       [0.34617934, 0.9561863 , 0.02010284, 0.95506495, 0.74124961],
       [0.07772438, 0.75107808, 0.30657956, 0.93263977, 0.56694998],
       [0.08711106, 0.78574825, 0.28022945, 0.29571563, 0.10432606],
       [0.41362251, 0.4953785 , 0.56257826, 0.50434297, 0.98202362]])

In [71]:
sumaTotal=array1.sum()
print(sumaTotal)

13.146625004109803


In [72]:
array1.min()

np.float64(0.020102844998806102)

In [73]:
array1.max()

np.float64(0.9820236177350607)

In [74]:
#Maximo por filas
array1.max(axis=0)

array([0.96720219, 0.9561863 , 0.62661212, 0.95506495, 0.98202362])

In [75]:
#Maximo por columnas
array1.max(axis=1)

array([0.96720219, 0.9561863 , 0.93263977, 0.78574825, 0.98202362])

In [76]:
#Suma acumulada
array1.cumsum(axis=1)

array([[0.96720219, 1.27117279, 1.89778491, 2.53717973, 2.98179387],
       [0.34617934, 1.30236564, 1.32246849, 2.27753343, 3.01878304],
       [0.07772438, 0.82880247, 1.13538203, 2.0680218 , 2.63497178],
       [0.08711106, 0.87285931, 1.15308876, 1.44880439, 1.55313045],
       [0.41362251, 0.90900102, 1.47157928, 1.97592224, 2.95794586]])

In [77]:
array1

array([[0.96720219, 0.3039706 , 0.62661212, 0.63939482, 0.44461414],
       [0.34617934, 0.9561863 , 0.02010284, 0.95506495, 0.74124961],
       [0.07772438, 0.75107808, 0.30657956, 0.93263977, 0.56694998],
       [0.08711106, 0.78574825, 0.28022945, 0.29571563, 0.10432606],
       [0.41362251, 0.4953785 , 0.56257826, 0.50434297, 0.98202362]])

In [78]:
#Media
np.mean(array1)

np.float64(0.5258650001643921)

In [79]:
#Mediana
np.median(array1)

np.float64(0.5043429662761413)

In [80]:
#Correlacion
np.corrcoef(array1)

array([[ 1.        , -0.54222875, -0.66727224, -0.6813095 , -0.45404506],
       [-0.54222875,  1.        ,  0.84062129,  0.45094646,  0.14075989],
       [-0.66727224,  0.84062129,  1.        ,  0.51613747,  0.14661019],
       [-0.6813095 ,  0.45094646,  0.51613747,  1.        , -0.33201664],
       [-0.45404506,  0.14075989,  0.14661019, -0.33201664,  1.        ]])

In [81]:
#Desviacion
np.std(array1)

np.float64(0.29791095499764236)

# Copiando arrays

In [82]:
array1=np.random.randint(21,size=(4,4))
array1

array([[13, 19, 11, 13],
       [12,  8,  5, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [83]:
#Crea una imagen del array, el valor cambiado se refleja en los dos
array_cop=array1.view()
array_cop

array([[13, 19, 11, 13],
       [12,  8,  5, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [84]:
np.array_equal(array1,array_cop)

True

In [85]:
#Modificamos un valor de la copia
array_cop[0,1]=99
array_cop

array([[13, 99, 11, 13],
       [12,  8,  5, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [86]:
#Modificamos un valor del original
array1[1,2]=88
array1

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [87]:
array_cop

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [88]:
#Creamos copia independiente
array_cop2 = np.copy(array1)
array_cop2

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [89]:
array_cop2[2,3]=77
array_cop2

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 77],
       [19, 11, 18, 14]], dtype=int32)

In [90]:
array1

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [91]:
array_cop2 = array1 * 3
array_cop2

array([[ 39, 297,  33,  39],
       [ 36,  24, 264,  60],
       [  9,  51,  21,  39],
       [ 57,  33,  54,  42]], dtype=int32)

In [92]:
array1

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [93]:
array_cop2=array1.copy()
array_cop2

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [94]:
array1

array([[13, 99, 11, 13],
       [12,  8, 88, 20],
       [ 3, 17,  7, 13],
       [19, 11, 18, 14]], dtype=int32)

In [95]:
np.array_equal(array1,array_cop2)

True

# Arrays, ordenamiento

In [96]:
array_1 = np.random.randint(41,size=(10,10))
array_1

array([[33,  2, 38, 29, 20,  9, 13, 32, 29,  2],
       [38,  1, 17, 22, 32, 13,  8, 35,  2, 32],
       [27, 23, 30, 14, 37, 16, 28, 37, 12, 15],
       [ 1, 15, 33,  1,  5, 14, 38, 18, 39, 33],
       [13, 38, 10,  2, 34, 34, 36, 23, 32,  4],
       [38, 14, 24, 11, 37, 11, 28, 38, 10, 12],
       [20, 11, 27, 14, 23, 34,  5, 18, 31, 24],
       [ 4, 12,  8, 40, 20, 28, 30,  1, 17, 28],
       [23, 29, 34, 34, 17, 29, 39, 33,  3, 24],
       [32, 23, 19, 31, 11, 31, 25, 23, 27, 12]], dtype=int32)

In [97]:
array_2 = np.random.randint(31,size=(10,10))
array_2

array([[26, 24,  7,  6, 23,  8, 14, 20, 15, 27],
       [30, 14, 25, 23,  9, 13, 21, 13, 10, 10],
       [25, 14,  6,  2,  5, 14, 27, 12, 29, 16],
       [30, 10, 11,  0, 30, 12, 20, 28, 25, 18],
       [26,  3, 10, 14, 22,  8, 28,  1,  7, 15],
       [11, 18,  5, 17, 22,  4, 15,  1, 20, 15],
       [29,  7,  1, 18, 10, 17,  8, 11,  6,  4],
       [19, 17, 13, 26,  8, 28, 12, 12, 29,  7],
       [16, 14, 27,  3, 29, 12, 21, 15, 30,  0],
       [17,  9, 13, 15, 30,  1, 23, 27, 17, 27]], dtype=int32)

In [98]:
array_1

array([[33,  2, 38, 29, 20,  9, 13, 32, 29,  2],
       [38,  1, 17, 22, 32, 13,  8, 35,  2, 32],
       [27, 23, 30, 14, 37, 16, 28, 37, 12, 15],
       [ 1, 15, 33,  1,  5, 14, 38, 18, 39, 33],
       [13, 38, 10,  2, 34, 34, 36, 23, 32,  4],
       [38, 14, 24, 11, 37, 11, 28, 38, 10, 12],
       [20, 11, 27, 14, 23, 34,  5, 18, 31, 24],
       [ 4, 12,  8, 40, 20, 28, 30,  1, 17, 28],
       [23, 29, 34, 34, 17, 29, 39, 33,  3, 24],
       [32, 23, 19, 31, 11, 31, 25, 23, 27, 12]], dtype=int32)

In [99]:
array_1.sort()
array_1

array([[ 2,  2,  9, 13, 20, 29, 29, 32, 33, 38],
       [ 1,  2,  8, 13, 17, 22, 32, 32, 35, 38],
       [12, 14, 15, 16, 23, 27, 28, 30, 37, 37],
       [ 1,  1,  5, 14, 15, 18, 33, 33, 38, 39],
       [ 2,  4, 10, 13, 23, 32, 34, 34, 36, 38],
       [10, 11, 11, 12, 14, 24, 28, 37, 38, 38],
       [ 5, 11, 14, 18, 20, 23, 24, 27, 31, 34],
       [ 1,  4,  8, 12, 17, 20, 28, 28, 30, 40],
       [ 3, 17, 23, 24, 29, 29, 33, 34, 34, 39],
       [11, 12, 19, 23, 23, 25, 27, 31, 31, 32]], dtype=int32)

In [100]:
array_1.sort(axis=1)
array_1

array([[ 2,  2,  9, 13, 20, 29, 29, 32, 33, 38],
       [ 1,  2,  8, 13, 17, 22, 32, 32, 35, 38],
       [12, 14, 15, 16, 23, 27, 28, 30, 37, 37],
       [ 1,  1,  5, 14, 15, 18, 33, 33, 38, 39],
       [ 2,  4, 10, 13, 23, 32, 34, 34, 36, 38],
       [10, 11, 11, 12, 14, 24, 28, 37, 38, 38],
       [ 5, 11, 14, 18, 20, 23, 24, 27, 31, 34],
       [ 1,  4,  8, 12, 17, 20, 28, 28, 30, 40],
       [ 3, 17, 23, 24, 29, 29, 33, 34, 34, 39],
       [11, 12, 19, 23, 23, 25, 27, 31, 31, 32]], dtype=int32)

In [101]:
array_2

array([[26, 24,  7,  6, 23,  8, 14, 20, 15, 27],
       [30, 14, 25, 23,  9, 13, 21, 13, 10, 10],
       [25, 14,  6,  2,  5, 14, 27, 12, 29, 16],
       [30, 10, 11,  0, 30, 12, 20, 28, 25, 18],
       [26,  3, 10, 14, 22,  8, 28,  1,  7, 15],
       [11, 18,  5, 17, 22,  4, 15,  1, 20, 15],
       [29,  7,  1, 18, 10, 17,  8, 11,  6,  4],
       [19, 17, 13, 26,  8, 28, 12, 12, 29,  7],
       [16, 14, 27,  3, 29, 12, 21, 15, 30,  0],
       [17,  9, 13, 15, 30,  1, 23, 27, 17, 27]], dtype=int32)

In [102]:
array_2.sort(axis=0)
array_2

array([[11,  3,  1,  0,  5,  1,  8,  1,  6,  0],
       [16,  7,  5,  2,  8,  4, 12,  1,  7,  4],
       [17,  9,  6,  3,  9,  8, 14, 11, 10,  7],
       [19, 10,  7,  6, 10,  8, 15, 12, 15, 10],
       [25, 14, 10, 14, 22, 12, 20, 12, 17, 15],
       [26, 14, 11, 15, 22, 12, 21, 13, 20, 15],
       [26, 14, 13, 17, 23, 13, 21, 15, 25, 16],
       [29, 17, 13, 18, 29, 14, 23, 20, 29, 18],
       [30, 18, 25, 23, 30, 17, 27, 27, 29, 27],
       [30, 24, 27, 26, 30, 28, 28, 28, 30, 27]], dtype=int32)

# Subconjuntos, indexado

In [109]:
array = np.random.randint(31,size=(10,10))
array

array([[15, 19, 11,  8, 20,  5,  1, 11, 16, 26],
       [26, 28, 11, 12, 11, 28,  0, 24,  1,  6],
       [13, 14, 29,  8,  9,  8, 17, 12, 11,  9],
       [19,  3,  1, 25,  9, 11, 30, 22, 26, 26],
       [ 7, 29, 20,  7,  7, 26, 25, 17, 19, 18],
       [ 9, 27,  2, 26, 19,  9, 12,  3,  2, 22],
       [15, 16,  7,  6, 14,  1, 29, 11,  5, 13],
       [27,  2, 25, 22, 23, 15,  0, 27,  6, 16],
       [ 3,  2,  1,  5, 23, 11, 21, 26, 27,  4],
       [ 9, 12, 15,  2, 25,  1, 18, 12, 16,  4]], dtype=int32)

In [110]:
#Seleccionamos elemento de la fila 2, columna 3
array[2,3]

np.int32(8)

In [111]:
#Slicing
array[1:4]

array([[26, 28, 11, 12, 11, 28,  0, 24,  1,  6],
       [13, 14, 29,  8,  9,  8, 17, 12, 11,  9],
       [19,  3,  1, 25,  9, 11, 30, 22, 26, 26]], dtype=int32)

In [112]:
array[1:4,2:5]

array([[11, 12, 11],
       [29,  8,  9],
       [ 1, 25,  9]], dtype=int32)

In [113]:
array[:1]

array([[15, 19, 11,  8, 20,  5,  1, 11, 16, 26]], dtype=int32)

In [114]:
array[3:4]

array([[19,  3,  1, 25,  9, 11, 30, 22, 26, 26]], dtype=int32)

In [115]:
array[:,4:5]

array([[20],
       [11],
       [ 9],
       [ 9],
       [ 7],
       [19],
       [14],
       [23],
       [23],
       [25]], dtype=int32)

In [116]:
array

array([[15, 19, 11,  8, 20,  5,  1, 11, 16, 26],
       [26, 28, 11, 12, 11, 28,  0, 24,  1,  6],
       [13, 14, 29,  8,  9,  8, 17, 12, 11,  9],
       [19,  3,  1, 25,  9, 11, 30, 22, 26, 26],
       [ 7, 29, 20,  7,  7, 26, 25, 17, 19, 18],
       [ 9, 27,  2, 26, 19,  9, 12,  3,  2, 22],
       [15, 16,  7,  6, 14,  1, 29, 11,  5, 13],
       [27,  2, 25, 22, 23, 15,  0, 27,  6, 16],
       [ 3,  2,  1,  5, 23, 11, 21, 26, 27,  4],
       [ 9, 12, 15,  2, 25,  1, 18, 12, 16,  4]], dtype=int32)

In [117]:
array[::-1]

array([[ 9, 12, 15,  2, 25,  1, 18, 12, 16,  4],
       [ 3,  2,  1,  5, 23, 11, 21, 26, 27,  4],
       [27,  2, 25, 22, 23, 15,  0, 27,  6, 16],
       [15, 16,  7,  6, 14,  1, 29, 11,  5, 13],
       [ 9, 27,  2, 26, 19,  9, 12,  3,  2, 22],
       [ 7, 29, 20,  7,  7, 26, 25, 17, 19, 18],
       [19,  3,  1, 25,  9, 11, 30, 22, 26, 26],
       [13, 14, 29,  8,  9,  8, 17, 12, 11,  9],
       [26, 28, 11, 12, 11, 28,  0, 24,  1,  6],
       [15, 19, 11,  8, 20,  5,  1, 11, 16, 26]], dtype=int32)

# Manipulacion de arrays

In [118]:
array = np.random.randint(10,size=(5,5))
array

array([[4, 0, 7, 1, 1],
       [6, 9, 6, 6, 6],
       [1, 0, 8, 9, 7],
       [6, 7, 6, 3, 1],
       [0, 3, 3, 2, 2]], dtype=int32)

In [119]:
#Traspuesta
array_t = np.transpose(array)
array_t

array([[4, 6, 1, 6, 0],
       [0, 9, 0, 7, 3],
       [7, 6, 8, 6, 3],
       [1, 6, 9, 3, 2],
       [1, 6, 7, 1, 2]], dtype=int32)

In [120]:
#Aplanar el array
array.ravel()

array([4, 0, 7, 1, 1, 6, 9, 6, 6, 6, 1, 0, 8, 9, 7, 6, 7, 6, 3, 1, 0, 3,
       3, 2, 2], dtype=int32)

In [121]:
#Cambiamos la forma pero no los datos
array.reshape(5,5)

array([[4, 0, 7, 1, 1],
       [6, 9, 6, 6, 6],
       [1, 0, 8, 9, 7],
       [6, 7, 6, 3, 1],
       [0, 3, 3, 2, 2]], dtype=int32)

In [122]:
array.reshape(1,25)

array([[4, 0, 7, 1, 1, 6, 9, 6, 6, 6, 1, 0, 8, 9, 7, 6, 7, 6, 3, 1, 0, 3,
        3, 2, 2]], dtype=int32)

In [123]:
array = np.random.randint(10,size=(4,24))
array

array([[1, 5, 9, 9, 3, 6, 1, 0, 3, 2, 7, 4, 2, 6, 4, 6, 8, 9, 9, 7, 6, 5,
        6, 0],
       [1, 5, 1, 4, 4, 1, 0, 5, 3, 0, 5, 8, 9, 1, 4, 7, 6, 5, 5, 5, 5, 1,
        9, 6],
       [5, 8, 8, 8, 6, 7, 6, 1, 1, 0, 1, 5, 4, 5, 7, 9, 0, 8, 4, 3, 1, 5,
        1, 8],
       [7, 4, 9, 3, 4, 1, 8, 1, 4, 0, 4, 2, 8, 2, 8, 9, 3, 1, 2, 9, 4, 2,
        7, 5]], dtype=int32)

In [124]:
array.reshape(12,8)

array([[1, 5, 9, 9, 3, 6, 1, 0],
       [3, 2, 7, 4, 2, 6, 4, 6],
       [8, 9, 9, 7, 6, 5, 6, 0],
       [1, 5, 1, 4, 4, 1, 0, 5],
       [3, 0, 5, 8, 9, 1, 4, 7],
       [6, 5, 5, 5, 5, 1, 9, 6],
       [5, 8, 8, 8, 6, 7, 6, 1],
       [1, 0, 1, 5, 4, 5, 7, 9],
       [0, 8, 4, 3, 1, 5, 1, 8],
       [7, 4, 9, 3, 4, 1, 8, 1],
       [4, 0, 4, 2, 8, 2, 8, 9],
       [3, 1, 2, 9, 4, 2, 7, 5]], dtype=int32)

In [125]:
#Otra forma
array.resize((8,12))
array

array([[1, 5, 9, 9, 3, 6, 1, 0, 3, 2, 7, 4],
       [2, 6, 4, 6, 8, 9, 9, 7, 6, 5, 6, 0],
       [1, 5, 1, 4, 4, 1, 0, 5, 3, 0, 5, 8],
       [9, 1, 4, 7, 6, 5, 5, 5, 5, 1, 9, 6],
       [5, 8, 8, 8, 6, 7, 6, 1, 1, 0, 1, 5],
       [4, 5, 7, 9, 0, 8, 4, 3, 1, 5, 1, 8],
       [7, 4, 9, 3, 4, 1, 8, 1, 4, 0, 4, 2],
       [8, 2, 8, 9, 3, 1, 2, 9, 4, 2, 7, 5]], dtype=int32)

In [126]:
#Añadir/ eliminar elementos
np.append(array, 34)

array([ 1,  5,  9,  9,  3,  6,  1,  0,  3,  2,  7,  4,  2,  6,  4,  6,  8,
        9,  9,  7,  6,  5,  6,  0,  1,  5,  1,  4,  4,  1,  0,  5,  3,  0,
        5,  8,  9,  1,  4,  7,  6,  5,  5,  5,  5,  1,  9,  6,  5,  8,  8,
        8,  6,  7,  6,  1,  1,  0,  1,  5,  4,  5,  7,  9,  0,  8,  4,  3,
        1,  5,  1,  8,  7,  4,  9,  3,  4,  1,  8,  1,  4,  0,  4,  2,  8,
        2,  8,  9,  3,  1,  2,  9,  4,  2,  7,  5, 34])

In [127]:
array=np.insert(array,2,99)
array

array([ 1,  5, 99,  9,  9,  3,  6,  1,  0,  3,  2,  7,  4,  2,  6,  4,  6,
        8,  9,  9,  7,  6,  5,  6,  0,  1,  5,  1,  4,  4,  1,  0,  5,  3,
        0,  5,  8,  9,  1,  4,  7,  6,  5,  5,  5,  5,  1,  9,  6,  5,  8,
        8,  8,  6,  7,  6,  1,  1,  0,  1,  5,  4,  5,  7,  9,  0,  8,  4,
        3,  1,  5,  1,  8,  7,  4,  9,  3,  4,  1,  8,  1,  4,  0,  4,  2,
        8,  2,  8,  9,  3,  1,  2,  9,  4,  2,  7,  5], dtype=int32)

In [149]:
#Borrado
array=np.delete(array,[1])
array

array([1, 6, 0, 1, 5, 1, 4, 4, 1, 0, 5, 3, 0, 5, 8, 9, 1, 4, 7, 6, 5, 5,
       5, 5, 1, 9, 6, 5, 8, 8, 8, 6, 7, 6, 1, 1, 0, 1, 5, 4, 5, 7, 9, 0,
       8, 4, 3, 1, 5, 1, 8, 7, 4, 9, 3, 4, 1, 8, 1, 4, 0, 4, 2, 8, 2, 8,
       9, 3, 1, 2, 9, 4, 2, 7, 5], dtype=int32)

In [150]:
array_1 = np.random.randint(10,size=(4,4))
array_1

array([[5, 3, 1, 8],
       [6, 3, 3, 8],
       [5, 0, 8, 3],
       [0, 7, 2, 8]], dtype=int32)

In [151]:
array_2 = np.random.randint(10,size=(4,4))
array_2

array([[3, 3, 7, 8],
       [4, 7, 4, 8],
       [7, 7, 6, 5],
       [4, 9, 8, 8]], dtype=int32)

In [152]:
#Combinar arrays
array_combinado = np.concatenate((array_1,array_2),axis=0)
array_combinado

array([[5, 3, 1, 8],
       [6, 3, 3, 8],
       [5, 0, 8, 3],
       [0, 7, 2, 8],
       [3, 3, 7, 8],
       [4, 7, 4, 8],
       [7, 7, 6, 5],
       [4, 9, 8, 8]], dtype=int32)

In [153]:
#Array vertical
array_combinado = np.vstack((array_1,array_2))
array_combinado

array([[5, 3, 1, 8],
       [6, 3, 3, 8],
       [5, 0, 8, 3],
       [0, 7, 2, 8],
       [3, 3, 7, 8],
       [4, 7, 4, 8],
       [7, 7, 6, 5],
       [4, 9, 8, 8]], dtype=int32)

In [154]:
#Otra forma
array_combinado=np.r_[array_1,array_2]
array_combinado

array([[5, 3, 1, 8],
       [6, 3, 3, 8],
       [5, 0, 8, 3],
       [0, 7, 2, 8],
       [3, 3, 7, 8],
       [4, 7, 4, 8],
       [7, 7, 6, 5],
       [4, 9, 8, 8]], dtype=int32)

In [155]:
#Combinado horizontal
array_combinado = np.hstack((array_1,array_2))
array_combinado

array([[5, 3, 1, 8, 3, 3, 7, 8],
       [6, 3, 3, 8, 4, 7, 4, 8],
       [5, 0, 8, 3, 7, 7, 6, 5],
       [0, 7, 2, 8, 4, 9, 8, 8]], dtype=int32)

In [156]:
#Otra forma
np.column_stack((array_1,array_2))

array([[5, 3, 1, 8, 3, 3, 7, 8],
       [6, 3, 3, 8, 4, 7, 4, 8],
       [5, 0, 8, 3, 7, 7, 6, 5],
       [0, 7, 2, 8, 4, 9, 8, 8]], dtype=int32)

In [157]:
#Otra forma
np.c_[array_1,array_2]

array([[5, 3, 1, 8, 3, 3, 7, 8],
       [6, 3, 3, 8, 4, 7, 4, 8],
       [5, 0, 8, 3, 7, 7, 6, 5],
       [0, 7, 2, 8, 4, 9, 8, 8]], dtype=int32)

In [158]:
#Splitting, corte array verticalmente
np.vsplit(array_1, 2)

[array([[5, 3, 1, 8],
        [6, 3, 3, 8]], dtype=int32),
 array([[5, 0, 8, 3],
        [0, 7, 2, 8]], dtype=int32)]

In [159]:
array_1

array([[5, 3, 1, 8],
       [6, 3, 3, 8],
       [5, 0, 8, 3],
       [0, 7, 2, 8]], dtype=int32)

In [160]:
#Corte horizontal
np.hsplit(array_1,2)

[array([[5, 3],
        [6, 3],
        [5, 0],
        [0, 7]], dtype=int32),
 array([[1, 8],
        [3, 8],
        [8, 3],
        [2, 8]], dtype=int32)]